"""empty message

Revision ID: a351c5e2ffc0
Revises: 73b0504aaa69
Create Date: 2017-04-14 08:44:53.450232

"""

# revision identifiers, used by Alembic.
revision = 'a351c5e2ffc0'
down_revision = '73b0504aaa69'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pk', name='user_pkey')
    )
    # ### end Alembic commands ###
